# Generated by Django 6.0.6 on 2026-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0002_alter_ourservice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='name',
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='our_service_photos'),
        ),
    ]
