# Generated by Django 6.0.6 on 2026-06-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0003_remove_ourservice_name_alter_ourservice_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='photo',
        ),
    ]
