# Generated by Django 6.0.6 on 2026-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('education', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('sort', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
