# Generated by Django 6.0.6 on 2026-06-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'ordering': ['sort']},
        ),
    ]
