# Generated by Django 6.0.6 on 2026-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_chefs', '0002_alter_chefs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chefs_photos'),
        ),
    ]
