# Generated by Django 6.0.6 on 2026-06-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeinfo',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-grade']},
        ),
    ]
