# Generated by Django 6.0.6 on 2026-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homeinfo_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
    ]
