# Generated by Django 6.0.6 on 2026-06-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['sort'], 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
