# Generated by Django 6.0.6 on 2026-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact_us_photos/'),
        ),
    ]
