# Generated by Django 6.0.6 on 2026-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_rename_adress_contactus_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
