# Generated by Django 6.0.6 on 2026-06-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0006_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
